FIND_PATH( IMGUI_INCLUDE_DIR imgui/imgui.h
	/usr/include
	/usr/local/include
	/opt/local/include
	"${CMAKE_SOURCE_DIR}/include"
)
FIND_LIBRARY( IMGUI_LIBRARY NAMES imgui
	PATHS
	/usr/lib64
	/usr/lib
	/usr/local/lib
	/opt/local/lib
	"${CMAKE_SOURCE_DIR}/lib"
)
IF(IMGUI_INCLUDE_DIR AND IMGUI_LIBRARY)
	SET( IMGUI_FOUND TRUE )
	SET( IMGUI_LIBRARIES ${IMGUI_LIBRARY} )
ENDIF(IMGUI_INCLUDE_DIR AND IMGUI_LIBRARY)
IF(IMGUI_FOUND)
	IF(NOT IMGUI_FIND_QUIETLY)
	MESSAGE(STATUS "Found IMGUI: ${IMGUI_LIBRARY}")
	ENDIF(NOT IMGUI_FIND_QUIETLY)
ELSE(IMGUI_FOUND)
	IF(IMGUI_FIND_REQUIRED)
	MESSAGE(FATAL_ERROR "Could not find libIMGUI")
	ENDIF(IMGUI_FIND_REQUIRED)
ENDIF(IMGUI_FOUND)