SET(_nlohmann_HEADER_SEARCH_DIRS
"/usr/include"
"/usr/local/include"
"${CMAKE_SOURCE_DIR}/include"
"C:/Program Files (x86)/nlohmann" )

# check environment variable
SET(_nlohmann_ENV_ROOT_DIR "$ENV{NLOHMANN_ROOT_DIR}")
IF(NOT NLOHMANN_ROOT_DIR AND _nlohmann_ENV_ROOT_DIR)
	SET(NLOHMANN_ROOT_DIR "${_nlohmann_ENV_ROOT_DIR}")
ENDIF(NOT NLOHMANN_ROOT_DIR AND _nlohmann_ENV_ROOT_DIR)
# put user specified location at beginning of search
IF(NLOHMANN_ROOT_DIR)
	SET(_nlohmann_HEADER_SEARCH_DIRS "${NLOHMANN_ROOT_DIR}"
	"${NLOHMANN_ROOT_DIR}/include"
	${_nlohmann_HEADER_SEARCH_DIRS})
ENDIF(NLOHMANN_ROOT_DIR)
# locate header
FIND_PATH(NLOHMANN_INCLUDE_DIR "nlohmann/json.hpp"
PATHS ${_nlohmann_HEADER_SEARCH_DIRS})
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(NLOHMANN DEFAULT_MSG
NLOHMANN_INCLUDE_DIR)
IF(NLOHMANN_FOUND)
	SET(NLOHMANN_INCLUDE_DIRS "${NLOHMANN_INCLUDE_DIR}")
	MESSAGE(STATUS "NLOHMANN_INCLUDE_DIR = ${NLOHMANN_INCLUDE_DIR}")
ENDIF(NLOHMANN_FOUND)